<?php

return [
    'ABJ' => 'Abidjan',
    'ABO' => 'Aboisso',
    'ABE' => 'Agboville',
    'AGN' => 'Agnibilékrou',
    'AKU' => 'Akoupé',
    'ANY' => 'Anyama',
    'BAM' => 'Bangolo',
    'BOU' => 'Bondoukou',
    'BKO' => 'Bongouanou',
    'BKE' => 'Bouaké',
    'BFL' => 'Bouaflé',
    'BDK' => 'Boundiali',
    'DAB' => 'Dabou',
    'DAL' => 'Daloa',
    'DAN' => 'Danané',
    'DAO' => 'Daoukro',
    'DIV' => 'Divo',
    'DUE' => 'Duékoué',
    'FER' => 'Ferkessédougou',
    'GAG' => 'Gagnoa',
    'GNB' => 'Grand-Bassam',
    'GLO' => 'Guiglo',
    'ISS' => 'Issia',
    'JAC' => 'Jacqueville',
    'KOR' => 'Katiola',
    'KRH' => 'Korhogo',
    'MAN' => 'Man',
    'MKN' => 'Mankono',
    'MBA' => 'Mbahiakro',
    'NDO' => "N'douci",
    'ODN' => 'Odienné',
    'OUM' => 'Oumé',
    'SAN' => 'Sassandra',
    'SEO' => 'Séguéla',
    'SIN' => 'Sinfra',
    'SPK' => 'San-Pédro',
    'TAB' => 'Tabou',
    'TAN' => 'Tanda',
    'TOU' => 'Touba',
    'TPL' => 'Toumodi',
    'VAV' => 'Vavoua',
    'YAK' => 'Yamoussoukro',
    'ZUE' => 'Zuénoula',
];